//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYNOITRU
    {
        public string MABENHNHAN { get; set; }
        public string MAPHONG { get; set; }
        public Nullable<System.DateTime> THOIGIANNHAPVIEN { get; set; }
        public Nullable<System.DateTime> THOIGIANXUATVIEN { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
