//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEUTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEUTRI()
        {
            this.XETNGHIEMs = new HashSet<XETNGHIEM>();
        }
    
        public string MADIEUTRI { get; set; }
        public string MAYSI { get; set; }
        public string MABENHNHAN { get; set; }
        public string MADONTHUOC { get; set; }
        public string LOAIDIEUTRI { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual GIADIEUTRI GIADIEUTRI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XETNGHIEM> XETNGHIEMs { get; set; }
        public virtual DONTHUOC DONTHUOC { get; set; }
        public virtual YSI YSI { get; set; }
    }
}
