//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAXETNGHIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAXETNGHIEM()
        {
            this.XETNGHIEMs = new HashSet<XETNGHIEM>();
        }
    
        public string MALOAIXETNGHIEM { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XETNGHIEM> XETNGHIEMs { get; set; }
    }
}
