//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYBENHVIENEntities : DbContext
    {
        public QUANLYBENHVIENEntities()
            : base("name=QUANLYBENHVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<BENHNHANSUDUNGTAISAN> BENHNHANSUDUNGTAISANs { get; set; }
        public virtual DbSet<DANGKYNOITRU> DANGKYNOITRUs { get; set; }
        public virtual DbSet<DIEUTRI> DIEUTRIs { get; set; }
        public virtual DbSet<DONTHUOC> DONTHUOCs { get; set; }
        public virtual DbSet<GIADIEUTRI> GIADIEUTRIs { get; set; }
        public virtual DbSet<GIAXETNGHIEM> GIAXETNGHIEMs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LICHKHAM> LICHKHAMs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHANVIENSUDUNGTAISAN> NHANVIENSUDUNGTAISANs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOANLETAN> TAIKHOANLETANs { get; set; }
        public virtual DbSet<TAIKHOANNHANVIENKYTHUAT> TAIKHOANNHANVIENKYTHUATs { get; set; }
        public virtual DbSet<TAIKHOANTRUONGKHOA> TAIKHOANTRUONGKHOAs { get; set; }
        public virtual DbSet<TAIKHOANGIAMDOC> TAIKHOANGIAMDOCs { get; set; }
        public virtual DbSet<TAISANCONG> TAISANCONGs { get; set; }
        public virtual DbSet<TUCTRUC> TUCTRUCs { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<XETNGHIEM> XETNGHIEMs { get; set; }
        public virtual DbSet<YSI> YSIs { get; set; }
    }
}
