//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.NHANVIENSUDUNGTAISANs = new HashSet<NHANVIENSUDUNGTAISAN>();
            this.TAIKHOANGIAMDOCs = new HashSet<TAIKHOANGIAMDOC>();
            this.TAIKHOANLETANs = new HashSet<TAIKHOANLETAN>();
            this.TAIKHOANNHANVIENKYTHUATs = new HashSet<TAIKHOANNHANVIENKYTHUAT>();
        }
    
        public string MANV { get; set; }
        public string TENNV { get; set; }
        public string CHUCVU { get; set; }
        public string NOILAMVIEC { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIENSUDUNGTAISAN> NHANVIENSUDUNGTAISANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANGIAMDOC> TAIKHOANGIAMDOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANLETAN> TAIKHOANLETANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANNHANVIENKYTHUAT> TAIKHOANNHANVIENKYTHUATs { get; set; }
    }
}
