//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.DANGKYNOITRUs = new HashSet<DANGKYNOITRU>();
            this.LICHKHAMs = new HashSet<LICHKHAM>();
            this.TUCTRUCs = new HashSet<TUCTRUC>();
        }
    
        public string MAPHONG { get; set; }
        public Nullable<byte> SOPHONG { get; set; }
        public Nullable<byte> TANG { get; set; }
        public string TENPHONG { get; set; }
        public Nullable<byte> SOLUONGYSI { get; set; }
        public Nullable<byte> SUCCHUA { get; set; }
        public Nullable<byte> SOGIUONGBENH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKYNOITRU> DANGKYNOITRUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHKHAM> LICHKHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUCTRUC> TUCTRUCs { get; set; }
    }
}
