//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANTRUONGKHOA
    {
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string MASO { get; set; }
    
        public virtual YSI YSI { get; set; }
    }
}
