//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFramwork2.Model1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAISANCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAISANCONG()
        {
            this.NHANVIENSUDUNGTAISANs = new HashSet<NHANVIENSUDUNGTAISAN>();
        }
    
        public string MATAISAN { get; set; }
        public string TENTAISAN { get; set; }
        public string LOAITAISAN { get; set; }
    
        public virtual BENHNHANSUDUNGTAISAN BENHNHANSUDUNGTAISAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIENSUDUNGTAISAN> NHANVIENSUDUNGTAISANs { get; set; }
    }
}
